// @ts-nocheck
/**
 * LLM Floor Plan Parser
 *
 * Takes hybrid user input (natural language + form fields) and produces
 * a structured FloorPlan schema. Uses a deterministic prompt to extract
 * architectural intent without calculating coordinates.
 *
 * If no LLM API key is configured, falls back to a smart deterministic
 * parser that handles common floor plan patterns.
 */

import { FloorPlanSchema, type FloorPlan, type UserInput } from "./schemas";

// Conversion constant
const SQFT_TO_SQMM = 92903.04;

/**
 * Parse user input into a structured FloorPlan.
 * Falls back to deterministic parsing if no LLM is available.
 */
export async function parseUserInput(input: UserInput): Promise<FloorPlan> {
  // For now, use deterministic parsing (LLM integration can be added later)
  return deterministicParse(input);
}

/**
 * Deterministic parser that intelligently converts user constraints
 * into a valid FloorPlan schema.
 */
function deterministicParse(input: UserInput): FloorPlan {
  const totalSqft = input.square_footage ?? extractSquareFootage(input.natural_language) ?? 1500;
  const numBedrooms = input.num_bedrooms ?? extractNumber(input.natural_language, /(\d+)\s*(?:bed(?:room)?s?|br|bdr)/i) ?? 3;
  const numBathrooms = input.num_bathrooms ?? extractNumber(input.natural_language, /(\d+)\s*(?:bath(?:room)?s?|ba)/i) ?? 2;
  const style = input.style ?? "bungalow";
  const isOpenPlan = style === "open_plan" || /open\s*(plan|layout|concept)/i.test(input.natural_language);

  // Calculate footprint dimensions (roughly 1.3:1 aspect ratio)
  const totalAreaSqmm = totalSqft * SQFT_TO_SQMM;
  const aspectRatio = 1.3;
  const widthMm = Math.round(Math.sqrt(totalAreaSqmm * aspectRatio));
  const lengthMm = Math.round(totalAreaSqmm / widthMm);

  // Generate rooms with proportional areas
  const rooms = generateRooms(totalSqft, numBedrooms, numBathrooms, isOpenPlan, input.natural_language);

  // Generate openings
  const openings = generateOpenings(rooms);

  const plan: FloorPlan = {
    project_title: "Auto-generated Floor Plan",
    architectural_style: style,
    exterior_wall_thickness_mm: 250,
    interior_wall_thickness_mm: 120,
    stories: 1,
    construction_notes: "Generated by deterministic parser.",
    footprint_dimensions: {
      width: widthMm,
      length: lengthMm,
      total_area_sqft_calculated: totalSqft,
    },
    rooms,
    openings,
  };

  // Validate with Zod
  return FloorPlanSchema.parse(plan);
}

/**
 * Generate rooms with intelligent area proportions
 */
function generateRooms(
  totalSqft: number,
  numBedrooms: number,
  numBathrooms: number,
  isOpenPlan: boolean,
  nlText: string
): FloorPlan["rooms"] {
  const rooms: FloorPlan["rooms"] = [];
  let allocatedSqft = 0;

  // Check for specific room mentions
  const hasGarage = /garage/i.test(nlText);
  const hasOffice = /office|study|den/i.test(nlText);
  const hasLaundry = /laundry|utility/i.test(nlText);
  const hasPantry = /pantry/i.test(nlText);
  const hasDining = !isOpenPlan || /dining/i.test(nlText);

  // Living area (larger if open plan)
  const livingArea = isOpenPlan ? totalSqft * 0.25 : totalSqft * 0.15;
  rooms.push({
    id: "living_room",
    name: isOpenPlan ? "Great Room" : "Living Room",
    target_area_sqft: Math.round(livingArea),
    preferred_adjacency: ["kitchen", ...(hasDining ? ["dining_room"] : [])],
  });
  allocatedSqft += livingArea;

  // Kitchen
  const kitchenArea = isOpenPlan ? totalSqft * 0.12 : totalSqft * 0.1;
  rooms.push({
    id: "kitchen",
    name: "Kitchen",
    target_area_sqft: Math.round(kitchenArea),
    preferred_adjacency: ["living_room", ...(hasDining ? ["dining_room"] : [])],
  });
  allocatedSqft += kitchenArea;

  // Dining room (skip if open plan merges it)
  if (hasDining && !isOpenPlan) {
    const diningArea = totalSqft * 0.08;
    rooms.push({
      id: "dining_room",
      name: "Dining Room",
      target_area_sqft: Math.round(diningArea),
      preferred_adjacency: ["kitchen", "living_room"],
    });
    allocatedSqft += diningArea;
  }

  // Master bedroom
  const masterArea = totalSqft * 0.12;
  rooms.push({
    id: "master_bedroom",
    name: "Master Bedroom",
    target_area_sqft: Math.round(masterArea),
    preferred_adjacency: ["master_bath"],
  });
  allocatedSqft += masterArea;

  // Master bath
  const masterBathArea = totalSqft * 0.05;
  rooms.push({
    id: "master_bath",
    name: "Master Bath",
    target_area_sqft: Math.round(masterBathArea),
    preferred_adjacency: ["master_bedroom"],
  });
  allocatedSqft += masterBathArea;

  // Additional bedrooms
  const bedroomArea = totalSqft * 0.09;
  for (let i = 1; i < numBedrooms; i++) {
    rooms.push({
      id: `bedroom_${i + 1}`,
      name: `Bedroom ${i + 1}`,
      target_area_sqft: Math.round(bedroomArea),
      preferred_adjacency: ["hallway"],
    });
    allocatedSqft += bedroomArea;
  }

  // Additional bathrooms
  const bathArea = totalSqft * 0.04;
  for (let i = 1; i < numBathrooms; i++) {
    rooms.push({
      id: `bathroom_${i + 1}`,
      name: `Bathroom ${i + 1}`,
      target_area_sqft: Math.round(bathArea),
      preferred_adjacency: [numBedrooms > 1 ? `bedroom_${i + 1}` : "hallway"],
    });
    allocatedSqft += bathArea;
  }

  // Optional rooms
  if (hasOffice) {
    const officeArea = totalSqft * 0.06;
    rooms.push({
      id: "office",
      name: "Home Office",
      target_area_sqft: Math.round(officeArea),
      preferred_adjacency: ["living_room"],
    });
    allocatedSqft += officeArea;
  }

  if (hasLaundry) {
    const laundryArea = totalSqft * 0.04;
    rooms.push({
      id: "laundry",
      name: "Laundry Room",
      target_area_sqft: Math.round(laundryArea),
      preferred_adjacency: ["kitchen"],
    });
    allocatedSqft += laundryArea;
  }

  if (hasGarage) {
    const garageArea = totalSqft * 0.15;
    rooms.push({
      id: "garage",
      name: "Garage",
      target_area_sqft: Math.round(garageArea),
      preferred_adjacency: ["kitchen"],
    });
    allocatedSqft += garageArea;
  }

  if (hasPantry) {
    const pantryArea = totalSqft * 0.025;
    rooms.push({
      id: "pantry",
      name: "Pantry",
      target_area_sqft: Math.round(pantryArea),
      preferred_adjacency: ["kitchen"],
    });
    allocatedSqft += pantryArea;
  }

  // Hallway / entry — absorb remaining space
  const remaining = totalSqft - allocatedSqft;
  if (remaining > 30) {
    rooms.push({
      id: "hallway",
      name: "Hallway / Entry",
      target_area_sqft: Math.round(Math.max(remaining, totalSqft * 0.05)),
      preferred_adjacency: ["living_room", "kitchen"],
    });
  }

  return rooms;
}

/**
 * Generate door and window openings between rooms
 */
function generateOpenings(rooms: FloorPlan["rooms"]): FloorPlan["openings"] {
  const openings: FloorPlan["openings"] = [];
  const roomIds = new Set(rooms.map((r) => r.id));

  // Add doors between adjacent rooms
  for (const room of rooms) {
    for (const adjId of room.preferred_adjacency) {
      if (!roomIds.has(adjId)) continue;

      // Avoid duplicate door pairs
      const existing = openings.find(
        (o) =>
          o.type === "door" &&
          ((o.connecting[0] === room.id && o.connecting[1] === adjId) ||
            (o.connecting[0] === adjId && o.connecting[1] === room.id))
      );
      if (existing) continue;

      openings.push({
        type: "door",
        connecting: [room.id, adjId],
        width_mm: room.id.includes("bath") || adjId.includes("bath") ? 760 : 900,
      });
    }
  }

  // Add windows to exterior-facing rooms (bedrooms, living, kitchen)
  for (const room of rooms) {
    if (
      room.id.includes("bedroom") ||
      room.id === "living_room" ||
      room.id === "kitchen" ||
      room.id === "master_bedroom" ||
      room.id === "office"
    ) {
      openings.push({
        type: "window",
        connecting: [room.id, "exterior"],
        width_mm: room.id === "living_room" ? 1800 : 1200,
      });
    }
  }

  return openings;
}

// ── Helper extractors ──

function extractSquareFootage(text: string): number | null {
  const match = text.match(
    /(\d[,\d]*)\s*(?:sq(?:uare)?\s*(?:ft|feet|foot)|sqft|sf)/i
  );
  if (match) {
    return parseInt(match[1].replace(/,/g, ""), 10);
  }
  return null;
}

function extractNumber(text: string, pattern: RegExp): number | null {
  const match = text.match(pattern);
  if (match) {
    return parseInt(match[1], 10);
  }
  return null;
}
